# Theme settings
doks:
    baseurl: /Mastering-the-Marketplace
    color_theme: msft # Available themes: blue (default), green, purple, red and yellow
    header:
        logo: 
            text: Mastering the Marketplace Learning Library
            # image: /images/Azure_Store_Marketplace_150.png
    footer:
        content:
            logo:
                text: 
                image:
            copyright: Copyright &copy; 2022. - Microsoft, Inc. <br>All rights reserved.
    google_analytics:
        tracking_code: G-QFBKKPKXNV

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/