site_name: Mastering the Marketplace
site_url: https://microsoft.github.io/Mastering-the-Marketplace/
repo_url: https://github.com/microsoft/Mastering-the-Marketplace
repo_name: microsoft/Mastering-the-Marketplace
edit_uri: ''
extra_css: 
    - stylesheets/extra.css

nav:
  - Courses by offer type:
    - Azure Managed Applications: '/Mastering-the-Marketplace/ama/'
    - Container offers for K8s apps: '/Mastering-the-Marketplace/container/'
    - SaaS: '/Mastering-the-Marketplace/saas/'
    - Virtual Machines: '/Mastering-the-Marketplace/vm/'
    - Teams: '/Mastering-the-Marketplace/teams/'
  - Bonus content:
    - SaaS Accelerator: '/Mastering-the-Marketplace/saas-accelerator/'
    - Partner Center: '/Mastering-the-Marketplace/partner-center/'
  - More resources:
    - ğŸŒ Choose your offer type: '/Mastering-the-Marketplace/misc/select-offer-type'
    - ğŸš¦ Learning paths: '/Mastering-the-Marketplace/learning-paths/'
    - ğŸ” For your customers: '/Mastering-the-Marketplace/learning-paths/customer'
    - ğŸ“† Marketplace Office Hours: 'https://microsoftcloudpartner.eventbuilder.com/MarketplaceOverviewandQAforPartners'
    - ğŸ—’ï¸ Site change log: '/Mastering-the-Marketplace/misc/change-log'
    - âœ‰ï¸ Contact us: 'https://forms.office.com/r/0gCrzhSMkw'

theme:
  features:
    - navigation.sections
    - navigation.expand
  name: material
  custom_dir: overrides
  palette: 
    primary: '#0078D4'
    accent: 'light blue'
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/brands/microsoft
  favicon: favicon.ico

extra: 
  homepage: https://microsoft.github.io/Mastering-the-Marketplace/
  generator: false
  analytics:
    provider: google
    property: G-QFBKKPKXNV

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - toc:
        permalink: "#"
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search:
        indexing: 'sections'