site_name: Mastering the Marketplace
site_url: https://microsoft.github.io/Mastering-the-Marketplace/
repo_url: https://github.com/microsoft/Mastering-the-Marketplace
repo_name: microsoft/Mastering-the-Marketplace
edit_uri: ''
extra_css: 
    - stylesheets/extra.css

nav:
  - SaaS: 'https://aka.ms/MasteringTheMarketplace/saas'
  - SaaS for developers: 'https://aka.ms/MasteringTheMarketplace/saasdev'
  - SaaS Accelerator: 'https://aka.ms/MasteringTheMarketplace/sa'
  - Managed Applications: 'https://aka.ms/MasteringTheMarketplace/ama'
  - Virtual Machines: 'https://aka.ms/MasteringTheMarketplace/vm'
  - Container offers for K8s apps: 'https://aka.ms/MasteringTheMarketplace/container'
  
  - Partner Center:
    - Private offers: 'https://aka.ms/MasteringTheMarketplace/po'
    - General topics: 'https://aka.ms/MasteringTheMarketplace/pc'
    - Creating offers: '/Mastering-the-Marketplace/partner-center/#creating-offers-in-partner-center'
    - Reporting and insights: '/Mastering-the-Marketplace/partner-center/#reporting-and-insights-in-partner-center'

  - Bonus content:
    - Doing business in the marketplace: '/Mastering-the-Marketplace/biz'
    - For customers: '/Mastering-the-Marketplace/learning-paths/customer'
    - Marketplace Minis: '/Mastering-the-Marketplace/misc/marketplace-minis'
  
  - More resources:
    - ğŸŒ Choose your offer type: '/Mastering-the-Marketplace/biz/select-offer-type'
    - ğŸ–¥ï¸ Live webinars: 'https://aka.ms/MTMwebinars'
    # - âš™ï¸ Technical Accelerators: '/Mastering-the-Marketplace/misc/accelerators'
    # - ğŸš¦ Learning paths: '/Mastering-the-Marketplace/learning-paths/'
    - ğŸ—’ï¸ Site change log: '/Mastering-the-Marketplace/misc/change-log'
    - âœ‰ï¸ Contact us: 'https://forms.office.com/r/0gCrzhSMkw'
  
theme:
  features:
    - navigation.sections
    - navigation.expand
  name: material
  custom_dir: overrides
  palette: 
    primary: '#0078D4'
    accent: 'light blue'
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/brands/microsoft
  favicon: favicon.ico

extra: 
  homepage: https://microsoft.github.io/Mastering-the-Marketplace/
  generator: false
  analytics:
    provider: google
    property: G-QFBKKPKXNV

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - toc:
        permalink: "#"
  # - pymdownx.emoji:
        # emoji_index: !!python/name:materialx.emoji.twemoji
        # emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search:
        indexing: 'titles'
